INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('1', '제목1', '내용1');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('2', '제목2', '내용2');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('3', '제목3', '내용3');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('4', '제목4', '내용4');